# -*- coding: utf-8 -*-
"""universal_asset_app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Un7bsTROCuMHmnah7xgM-XVCP_Qnzx1s
"""

!pip install yfinance forex-python pycoingecko > /dev/null

import pandas as pd
import numpy as np
import yfinance as yf

from forex_python.converter import CurrencyRates
from pycoingecko import CoinGeckoAPI

cg = CoinGeckoAPI()

!pip install yfinance forex-python pycoingecko > /dev/null
import yfinance as yf
from forex_python.converter import CurrencyRates
from pycoingecko import CoinGeckoAPI

cg = CoinGeckoAPI()
c = CurrencyRates()

def detect_asset_type(user_input):
    t = user_input.upper().strip()
    try:
        stock = yf.Ticker(t)
        info = stock.info
        if info.get("regularMarketPrice") is not None:
            return "ETF" if info.get("quoteType")=="ETF" else "STOCK"
    except: pass

    cryptos = ["BTC","ETH","SOL","XRP","ADA"]
    if t in cryptos: return "CRYPTO"
    commodities = ["GOLD","SILVER","OIL","COPPER"]
    if t in commodities: return "COMMODITY"
    if len(t)==6 and t.isalpha(): return "CURRENCY"
    if t in ["US10Y","US2Y","US30Y","USGG"]: return "BOND"
    return "UNKNOWN"

def fetch_basic_data(asset, asset_type):
    try:
        if asset_type in ["STOCK","ETF"]:
            data = yf.Ticker(asset).info
            return {"price":data.get("regularMarketPrice"),
                    "name":data.get("longName","Unknown"),
                    "exchange":data.get("exchange","Unknown")}
        if asset_type=="CRYPTO":
            crypto_id={"BTC":"bitcoin","ETH":"ethereum","SOL":"solana",
                       "XRP":"ripple","ADA":"cardano"}.get(asset)
            market=cg.get_price(ids=crypto_id,vs_currencies='usd')
            return {"price":market[crypto_id]["usd"],"name":crypto_id}
        if asset_type=="COMMODITY": return {"price":"N/A","name":asset}
        if asset_type=="CURRENCY":
            base, quote = asset[0:3], asset[3:6]
            price=c.get_rate(base,quote)
            return {"price":price,"name":f"{base}/{quote}"}
        if asset_type=="BOND": return {"price":"N/A","name":asset}
    except: return {"price":None,"name":"Unknown"}
    return None

def analyze_asset_basic(user_input):
    asset_type=detect_asset_type(user_input)
    data=fetch_basic_data(user_input.upper(),asset_type)
    return {"input":user_input,"asset_type":asset_type,"basic_data":data}

# TEST
print(analyze_asset_basic("AAPL"))
print(analyze_asset_basic("RELIANCE.NS"))
print(analyze_asset_basic("BTC"))
print(analyze_asset_basic("GOLD"))

# -----------------------------
# UNIVERSAL ASSET ANALYZER - PORTFOLIO READY
# -----------------------------

# 1️⃣ Install required libraries
!pip install yfinance forex-python pycoingecko ta plotly > /dev/null

# 2️⃣ Imports
import yfinance as yf
from forex_python.converter import CurrencyRates
from pycoingecko import CoinGeckoAPI
import pandas as pd
from ta.momentum import RSIIndicator
import plotly.graph_objects as go

cg = CoinGeckoAPI()
c = CurrencyRates()

# 3️⃣ Detect asset type
def detect_asset_type(asset):
    t = asset.upper().strip()
    try:
        info = yf.Ticker(t).info
        if info.get("regularMarketPrice") is not None:
            return "ETF" if info.get("quoteType")=="ETF" else "STOCK"
    except: pass
    if t in ["BTC","ETH","SOL","XRP","ADA"]: return "CRYPTO"
    if t in ["GOLD","SILVER","OIL","COPPER"]: return "COMMODITY"
    if len(t)==6 and t.isalpha(): return "CURRENCY"
    if t in ["US10Y","US2Y","US30Y","USGG"]: return "BOND"
    return "UNKNOWN"

# 4️⃣ Fetch basic data
def fetch_basic_data(asset, asset_type):
    try:
        if asset_type in ["STOCK","ETF"]:
            info = yf.Ticker(asset).info
            return {"name": info.get("longName","Unknown"),
                    "price": info.get("regularMarketPrice"),
                    "exchange": info.get("exchange","Unknown")}
        if asset_type=="CRYPTO":
            crypto_id = {"BTC":"bitcoin","ETH":"ethereum","SOL":"solana",
                         "XRP":"ripple","ADA":"cardano"}.get(asset)
            market = cg.get_price(ids=crypto_id, vs_currencies='usd')
            return {"name": crypto_id, "price": market[crypto_id]["usd"]}
        if asset_type=="COMMODITY": return {"name": asset, "price": "N/A"}
        if asset_type=="CURRENCY":
            base, quote = asset[0:3], asset[3:6]
            price = c.get_rate(base, quote)
            return {"name": f"{base}/{quote}", "price": price}
        if asset_type=="BOND": return {"name": asset, "price": "N/A"}
    except: return {"name":"Unknown","price":None}

# 5️⃣ Fetch price history
def fetch_price_history(asset, period="3mo", interval="1d"):
    try:
        asset_type = detect_asset_type(asset)
        yf_asset = asset
        if asset_type=="CRYPTO": yf_asset = asset+"-USD"
        df = yf.download(yf_asset, period=period, interval=interval, progress=False)
        if df.empty or 'Close' not in df.columns:
            return None
        return df
    except:
        return None

# 6️⃣ Safe RSI function
def safe_rsi(close, window=14):
    if isinstance(close, pd.DataFrame):
        close = close.iloc[:,0]
    close = close.dropna()
    if len(close) < window:
        return pd.Series([float('nan')]*len(close), index=close.index)
    try:
        rsi = RSIIndicator(close, window).rsi()
        return rsi
    except:
        return pd.Series([float('nan')]*len(close), index=close.index)

# 7️⃣ Technical analysis (crash-proof)
def analyze_technical(df):
    result = {"support":None,"resistance":None,"trend":"N/A","RSI":"N/A","volatility":"N/A"}

    if df is None or df.empty or 'Close' not in df.columns:
        return result

    # Ensure 1D Series
    close = df['Close']
    if isinstance(close, pd.DataFrame):
        close = close.iloc[:,0]
    close = close.dropna()
    if len(close) == 0: return result

    # Support & Resistance
    result["support"] = float(close[-20:].min()) if len(close) >= 1 else None
    result["resistance"] = float(close[-20:].max()) if len(close) >= 1 else None

    # Moving averages
    ma20 = close.rolling(20).mean().iloc[-1] if len(close) >= 20 else None
    ma50 = close.rolling(50).mean().iloc[-1] if len(close) >= 50 else None
    try: ma20 = float(ma20)
    except: ma20 = None
    try: ma50 = float(ma50)
    except: ma50 = None

    # Trend
    if ma20 is not None and ma50 is not None:
        if ma20 > ma50: result["trend"] = "UPTREND"
        elif ma20 < ma50: result["trend"] = "DOWNTREND"
        else: result["trend"] = "NEUTRAL"
    else:
        result["trend"] = "NEUTRAL"

    # RSI
    try:
        rsi_val = safe_rsi(close,14).iloc[-1]
        result["RSI"] = float(rsi_val) if not pd.isna(rsi_val) else "N/A"
    except:
        result["RSI"] = "N/A"

    # Volatility
    try:
        result["volatility"] = str(round(float(close.pct_change().std())*100,2))+"%"
    except:
        result["volatility"] = "N/A"

    return result

# 8️⃣ Fundamental analysis
def fundamental_analysis(asset, asset_type):
    try:
        if asset_type=="STOCK":
            info = yf.Ticker(asset).info
            return {"company": info.get("longName","Unknown"),
                    "PE_ratio": info.get("trailingPE","N/A"),
                    "debt_to_equity": info.get("debtToEquity","N/A"),
                    "profit_margin": info.get("profitMargins","N/A")}
        if asset_type=="ETF":
            info = yf.Ticker(asset).info
            return {"name": info.get("longName","Unknown"),
                    "top_holdings": info.get("topHoldings",[]),
                    "expense_ratio": info.get("expenseRatio","N/A")}
        if asset_type=="CRYPTO":
            return {"project":asset,"market_cap":"Use API","community":"Use API","developer_activity":"Use API"}
        if asset_type=="COMMODITY":
            return {"supply_demand":"Check economic indicators","usd_strength":"Check USD index"}
        if asset_type=="BOND":
            return {"credit_rating":"AAA","yield":"4%","risk":"Low"}
    except: return {"info":"Unavailable"}

# 9️⃣ Decision & risk
def make_decision(asset_type, fundamental, technical):
    decision="HOLD"; risk="Unknown"
    try:
        trend = technical.get("trend")
        if asset_type=="STOCK":
            pe = fundamental.get("PE_ratio")
            decision="BUY" if pe not in [None,"N/A"] and trend=="UPTREND" else "WAIT"
            risk="Low" if trend=="UPTREND" else "Medium"
        if asset_type=="ETF": decision="BUY"; risk="Medium"
        if asset_type=="CRYPTO": decision="SPECULATE"; risk="High"
        if asset_type=="COMMODITY": decision="BUY" if trend=="UPTREND" else "WAIT"; risk="Medium"
        if asset_type=="BOND": decision="BUY"; risk="Low"
    except: decision="HOLD"; risk="Unknown"
    return {"action":decision,"risk":risk}

# 🔟 Interactive chart with Plotly
def plot_interactive_chart(asset, df, technical):
    if df is None or df.empty or 'Close' not in df.columns:
        print("No price data available.")
        return

    # Ensure 1D Series
    close = df['Close']
    if isinstance(close, pd.DataFrame):
        close = close.iloc[:,0]
    close = close.dropna()

    volume = df['Volume'] if 'Volume' in df.columns else pd.Series([0]*len(df), index=df.index)
    if isinstance(volume, pd.DataFrame):
        volume = volume.iloc[:,0]

    support = technical.get("support")
    resistance = technical.get("resistance")
    trend = technical.get("trend")

    ma20 = close.rolling(20).mean()
    ma50 = close.rolling(50).mean()

    rsi = safe_rsi(close,14)

    breakout_up = close[close > resistance] if resistance is not None else pd.Series()
    breakout_down = close[close < support] if support is not None else pd.Series()

    vol_thresh = volume.quantile(0.95)
    high_vol = volume[volume >= vol_thresh]

    # -----------------------------
    # 1️⃣ Price + MA + Support/Resistance
    # -----------------------------
    fig_price = go.Figure()
    fig_price.add_trace(go.Scatter(x=df.index, y=close, mode='lines', name='Close', line=dict(color='blue')))
    fig_price.add_trace(go.Scatter(x=df.index, y=ma20, mode='lines', name='MA20', line=dict(color='orange')))
    fig_price.add_trace(go.Scatter(x=df.index, y=ma50, mode='lines', name='MA50', line=dict(color='purple')))

    if support is not None:
        fig_price.add_trace(go.Scatter(x=df.index, y=[support]*len(df), mode='lines', name='Support',
                                       line=dict(dash='dash', color='green')))
    if resistance is not None:
        fig_price.add_trace(go.Scatter(x=df.index, y=[resistance]*len(df), mode='lines', name='Resistance',
                                       line=dict(dash='dash', color='red')))

    if not breakout_up.empty:
        fig_price.add_trace(go.Scatter(x=breakout_up.index, y=breakout_up, mode='markers', name='Breakout Up',
                                       marker=dict(color='orange', size=10, symbol='triangle-up')))
    if not breakout_down.empty:
        fig_price.add_trace(go.Scatter(x=breakout_down.index, y=breakout_down, mode='markers', name='Breakout Down',
                                       marker=dict(color='purple', size=10, symbol='triangle-down')))

    fig_price.update_layout(title=f"{asset} Price & Trend", xaxis_title="Date", yaxis_title="Price",
                            template='plotly_white')
    fig_price.show()

    # -----------------------------
    # 2️⃣ Volume chart
    # -----------------------------
    fig_vol = go.Figure()
    fig_vol.add_trace(go.Bar(x=df.index, y=volume, name='Volume', marker_color='lightblue'))
    if not high_vol.empty:
        fig_vol.add_trace(go.Bar(x=high_vol.index, y=high_vol, name='High Volume', marker_color='blue'))
    fig_vol.update_layout(title=f"{asset} Trading Volume", xaxis_title="Date", yaxis_title="Volume",
                          template='plotly_white')
    fig_vol.show()

    # -----------------------------
    # 3️⃣ RSI chart
    # -----------------------------
    fig_rsi = go.Figure()
    fig_rsi.add_trace(go.Scatter(x=rsi.index, y=rsi, mode='lines', name='RSI', line=dict(color='magenta')))
    fig_rsi.add_hline(y=70, line_dash="dash", line_color="red")
    fig_rsi.add_hline(y=30, line_dash="dash", line_color="green")
    fig_rsi.update_layout(title=f"{asset} RSI (14)", xaxis_title="Date", yaxis_title="RSI",
                          template='plotly_white')
    fig_rsi.show()

    # -----------------------------
    # Automated explanations
    # -----------------------------
    print("\n=== Automated Explanations ===")
    if not breakout_up.empty:
        print(f"- Price broke resistance at {resistance:.2f}, indicating bullish momentum.")
    if not breakout_down.empty:
        print(f"- Price fell below support at {support:.2f}, indicating bearish signal.")
    if not high_vol.empty:
        print(f"- High trading volume detected on {len(high_vol)} day(s), showing strong market interest.")
    if trend=="UPTREND":
        print(f"- Trend is currently UPTREND according to MA20 > MA50.")
    elif trend=="DOWNTREND":
        print(f"- Trend is currently DOWNTREND according to MA20 < MA50.")
    else:
        print("- Trend is NEUTRAL.")

# 🔹 Main function
def analyze_asset(asset):
    asset_type = detect_asset_type(asset)
    basic = fetch_basic_data(asset, asset_type)
    df = fetch_price_history(asset)
    technical = analyze_technical(df)
    fundamental = fundamental_analysis(asset, asset_type)
    decision = make_decision(asset_type, fundamental, technical)

    print(f"\n===== UNIVERSAL ASSET ANALYSIS: {asset} =====")
    print(f"Asset Type: {asset_type}")
    print(f"Basic Info: {basic}")
    print(f"Technical Analysis: {technical}")
    print(f"Fundamental Analysis: {fundamental}")
    print(f"Decision & Risk: {decision}\n")

    plot_interactive_chart(asset, df, technical)

# 🔹 User input
asset_input = input("Type any asset (Stock, ETF, Crypto, Commodity, Bond, Currency): ")
analyze_asset(asset_input)

!pip install Streamlit

!pip install pyngrok
!streamlit run universal_asset_app.py & npx localtunnel --port 8501

# 1️⃣ Install required packages
# -----------------------------
# pip install streamlit yfinance ta plotly pandas requests

# -----------------------------
# 2️⃣ Import libraries
# -----------------------------
import streamlit as st
import yfinance as yf
import pandas as pd
import numpy as np
import plotly.graph_objects as go
from ta.momentum import RSIIndicator
import requests

# -----------------------------
# 3️⃣ Asset type detection
# -----------------------------
def detect_asset_type(ticker):
    ticker = ticker.upper().strip()

    # Crypto (simple list example, can extend)
    crypto_list = ['BTC-USD','ETH-USD','ADA-USD','SOL-USD','XRP-USD']
    if ticker in crypto_list:
        return 'CRYPTO'

    # Bonds (example)
    bonds_list = ['US10Y','US2Y','US30Y','USGG']
    if ticker in bonds_list:
        return 'BOND'

    # Commodities (example)
    commodities_list = ['GOLD','SILVER','OIL','COPPER']
    if ticker in commodities_list:
        return 'COMMODITY'

    # ETFs (example)
    etf_prefix = ['SPY','QQQ','IWM','VTI']
    if any(ticker.startswith(p) for p in etf_prefix):
        return 'ETF'

    # Currencies (Forex pairs)
    if '/' in ticker or len(ticker)==6:
        return 'CURRENCY'

    # Default to STOCK
    return 'STOCK'

# -----------------------------
# 4️⃣ Fetch price data
# -----------------------------
def fetch_price_data(ticker, asset_type):
    if asset_type in ['STOCK','ETF','BOND','COMMODITY']:
        df = yf.download(ticker, period="1y", interval="1d", progress=False)
    elif asset_type == 'CRYPTO':
        df = yf.download(ticker, period="1y", interval="1d", progress=False)
    else:
        st.warning(f"Asset type {asset_type} not supported for price chart yet.")
        df = pd.DataFrame()
    if df.empty:
        st.warning(f"No data found for {ticker}")
    return df

# -----------------------------
# 5️⃣ Technical indicators
# -----------------------------
def add_technical_indicators(df):
    close = df['Close']
    if isinstance(close, pd.DataFrame):
        close = close.iloc[:,0]

    df['MA20'] = close.rolling(20).mean()
    df['MA50'] = close.rolling(50).mean()
    df['RSI'] = RSIIndicator(close,14).rsi()
    return df

# -----------------------------
# 6️⃣ Snapshot tables
# -----------------------------
def snapshot_tables(df):
    last_5 = df.tail(5)[['Open','High','Low','Close','Volume','MA20','MA50','RSI']]
    last_1y_5 = df.resample('2M').last()[['Open','High','Low','Close','Volume','MA20','MA50','RSI']].tail(5)
    return last_5, last_1y_5

# -----------------------------
# 7️⃣ Plot charts
# -----------------------------
def plot_charts(df, ticker):
    close = df['Close']
    if isinstance(close, pd.DataFrame):
        close = close.iloc[:,0]
    close = close.dropna()
    volume = df['Volume'] if 'Volume' in df.columns else pd.Series([0]*len(df), index=df.index)
    if isinstance(volume, pd.DataFrame):
        volume = volume.iloc[:,0]

    ma20 = df['MA20']
    ma50 = df['MA50']
    rsi = df['RSI']

    support = close.min()
    resistance = close.max()

    trend = "UPTREND" if ma20.iloc[-1] > ma50.iloc[-1] else "DOWNTREND" if ma20.iloc[-1] < ma50.iloc[-1] else "NEUTRAL"

    # Price chart
    fig_price = go.Figure()
    fig_price.add_trace(go.Scatter(x=df.index, y=close, mode='lines', name='Close', line=dict(color='blue')))
    fig_price.add_trace(go.Scatter(x=df.index, y=ma20, mode='lines', name='MA20', line=dict(color='orange')))
    fig_price.add_trace(go.Scatter(x=df.index, y=ma50, mode='lines', name='MA50', line=dict(color='purple')))
    fig_price.add_trace(go.Scatter(x=df.index, y=[support]*len(df), mode='lines', name='Support',
                                   line=dict(dash='dash', color='green')))
    fig_price.add_trace(go.Scatter(x=df.index, y=[resistance]*len(df), mode='lines', name='Resistance',
                                   line=dict(dash='dash', color='red')))
    st.plotly_chart(fig_price, use_container_width=True)

    # Volume chart
    fig_vol = go.Figure()
    fig_vol.add_trace(go.Bar(x=df.index, y=volume, name='Volume', marker_color='lightblue'))
    st.plotly_chart(fig_vol, use_container_width=True)

    # RSI chart
    fig_rsi = go.Figure()
    fig_rsi.add_trace(go.Scatter(x=rsi.index, y=rsi, mode='lines', name='RSI', line=dict(color='magenta')))
    fig_rsi.add_hline(y=70, line_dash="dash", line_color="red")
    fig_rsi.add_hline(y=30, line_dash="dash", line_color="green")
    st.plotly_chart(fig_rsi, use_container_width=True)

    # Automated explanation
    st.subheader("Automated Explanation")
    st.write(f"- Trend based on MA20 & MA50: **{trend}**")
    st.write(f"- Support: {support:.2f}, Resistance: {resistance:.2f}")
    if close.iloc[-1] > resistance:
        st.write(f"- Price is above resistance → potential bullish breakout")
    if close.iloc[-1] < support:
        st.write(f"- Price is below support → potential bearish signal")

# -----------------------------
# 8️⃣ Streamlit UI
# -----------------------------
st.title("🌍 Universal Asset Analyzer")

ticker_input = st.text_input("Type any ticker (Stock, ETF, Crypto, Commodity, Bond):", "AAPL")

if ticker_input:
    asset_type = detect_asset_type(ticker_input)
    st.write(f"**Detected Asset Type:** {asset_type}")

    df = fetch_price_data(ticker_input, asset_type)
    if not df.empty:
        df = add_technical_indicators(df)
        last_5, last_1y_5 = snapshot_tables(df)

        st.subheader("📊 Last 5 Days")
        st.dataframe(last_5)

        st.subheader("📈 Last 1 Year (5 sample points)")
        st.dataframe(last_1y_5)

        plot_charts(df, ticker_input)

